on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:YXL76/OS-SummerCamp2021-Stage1.git"
          destination_repo: "git@codechina.csdn.net:weixin_43918902/os-summercamp2021-stage1.git"

          source_branch: "refs/remotes/source/*"
          destination_branch: "refs/heads/*"

          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
